version: '2'

services:
    
### Workspace Utilities Container ###########################

    workspace:        
        build:
            context: ./workspace
            args:
                - INSTALL_MONGO=false
                - INSTALL_PHPREDIS=false
                - INSTALL_XDEBUG=false
                - INSTALL_NODE=false
                - COMPOSER_GLOBAL_INSTALL=false
                - PUID=1000
                - PGID=1000
        volumes_from:
            - volumes_source
        tty: true

### PHP-FPM Container #######################################

    php-fpm:
        
        build:
            context: ./php-fpm
            args:
                - INSTALL_MONGO=true
                - INSTALL_PHPREDIS=true
                - INSTALL_XDEBUG=false
            dockerfile: Dockerfile-70
        volumes_from:
            - volumes_source
        links:
            - workspace
            - mongo
            - redis

### Nginx Server Container ##################################

    nginx:
        
        build:
            context: ./nginx
            args:
                - PHP_UPSTREAM=php-fpm
        volumes_from:
            - volumes_source
        volumes:
            - ./logs/nginx/:/var/log/nginx
        ports:
            - "${DOCKER_APP_HOST}:${NGINX_HTTP_PORT}:80"
            - "${DOCKER_APP_HOST}:${NGINX_SSL_PORT}:443"
        links:
            - php-fpm
            - node


### Nodejs Container #########################################

    node:
        
        build: ./node
        ports:
            - "${DOCKER_APP_HOST}:${DOCKER_NODE_PORT}:3000"
        volumes_from:
            - volumes_source
        volumes:
            - ../app/Rawdata/:/src
        links:
            - mongo

### MongoDB Container #######################################

    mongo:
        
        build: ./mongo
        ports:
            - "${DOCKER_APP_HOST}:${DOCKER_MONGO_PORT}:27017"
        volumes_from:
            - volumes_data

### Redis Container #########################################

    redis:
        
        ulimits:
              nproc: 65535
              nofile:
                soft: 20000
                hard: 40000        
        build: ./redis
        volumes_from:
            - volumes_data
        ports:
            - "${DOCKER_APP_HOST}:${DOCKER_REDIS_PORT}:6379"


### Laravel Application Code Container ######################

    volumes_source:
        build: ./volumes/application
        volumes:
            - ../:/var/www/laravel

### Databases Data Container ################################

    volumes_data:
        build: ./volumes/data
        volumes:
            - ./data/redis:/data
            - ./data/mongo:/data/mnch

### Add more Containers below ###############################
