version: '2'

services:
    
### Workspace Utilities Container ###########################

    workspace:
        env_file:
            - ../.env
        build:
            context: ./workspace
            args:
                - INSTALL_MONGO=false
                - INSTALL_PHPREDIS=false
                - INSTALL_XDEBUG=false
                - INSTALL_NODE=false
                - COMPOSER_GLOBAL_INSTALL=false
                - PUID=1000
                - PGID=1000
        volumes_from:
            - volumes_source
        tty: true

### PHP-FPM Container #######################################

    php-fpm:
        env_file:
            - ../.env
        build:
            context: ./php-fpm
            args:
                - INSTALL_MONGO=true
                - INSTALL_PHPREDIS=true
                - INSTALL_XDEBUG=false
            dockerfile: Dockerfile-70
        volumes_from:
            - volumes_source
        links:
            - workspace
            - mongo
            - redis

### MongoDB Container #######################################

    mongo:
        env_file:
            - ../.env
        build: ./mongo
        ports:
            - "${DOCKER_APP_HOST}:${DOCKER_MONGO_PORT}:27017"
        volumes_from:
            - volumes_data

### Redis Container #########################################

    redis:
        env_file:
            - ../.env
        ulimits:
              nproc: 65535
              nofile:
                soft: 20000
                hard: 40000        
        build: ./redis
        volumes_from:
            - volumes_data
        ports:
            - "${DOCKER_APP_HOST}:${DOCKER_REDIS_PORT}:6379"

### Caddy Server Container ##################################

    caddy:
        env_file:
            - ../.env
        ulimits:
          nproc: 65535
          nofile:
            soft: 20000
            hard: 40000       
        build: ./caddy
        volumes_from:
            - volumes_source
        ports:
            - "${DOCKER_APP_HOST}:${CADDY_HTTP_PORT}:80"
            - "${DOCKER_APP_HOST}:${CADDY_SSL_PORT}:443"
            - "${DOCKER_APP_HOST}:${CADDY_CONFIG_PORT}:2015"
        volumes:
            - ./caddy/Caddyfile:/etc/Caddyfile
        links:
            - php-fpm


### Laravel Application Code Container ######################

    volumes_source:
        build: ./volumes/application
        volumes:
            - ../:/var/www/laravel

### Databases Data Container ################################

    volumes_data:
        build: ./volumes/data
        volumes:
            - ./data/redis:/data
            - ./data/mongo:/data/mnch

### Add more Containers below ###############################
